/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Place } from './place';


export interface Device { 
    id?: number;
    name?: string;
    lastUpdated?: string;
    username?: string;
    password?: string;
    state?: Place;
}

