/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeviceDto { 
    id?: number;
    name?: string;
    lastUpdated?: string;
    username?: string;
    password?: string;
}

