/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Device } from './device';


export interface Place { 
    id?: number;
    name?: string;
    description?: string;
    devices?: Array<Device>;
}

