/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeviceShortView } from './deviceShortView';


export interface PlaceView { 
    devices?: Array<DeviceShortView>;
    name?: string;
    id?: number;
}

